# Generated by Django 4.1 on 2022-09-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rightssupport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RightsSupport',
        ),
    ]
